version: "3.9"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./products.db:/app/products.db
    env_file:
      - .env

  aiogram_bot:
    build:
      context: .
      dockerfile: dockerfile.bot
    volumes:
      - ./products.db:/app/products.db
    env_file:
      - .env

